[package]
name = "minecraft-ws"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.52", features = ["derive"] }
jsonrpsee = { version = "0.26.0", features = ["ws-client"] }
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
